# Generated by Django 4.2.3 on 2023-10-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_grappling_participation_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="grappling_participation_count",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="jiu_jitsu_participation_count",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="kick_boxing_participation_count",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="yoga_participation_count",
        ),
    ]
