# Generated by Django 4.2.3 on 2023-10-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_grappling_participation_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="grappling_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="jiu_jitsu_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="kick_boxing_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="yoga_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
