# Generated by Django 4.2.3 on 2023-10-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_customuser_grappling_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_limit",
            field=models.IntegerField(default=100000000000),
        ),
    ]
