# Generated by Django 4.2.3 on 2023-10-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_user_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_limit",
            field=models.IntegerField(default=1000),
        ),
    ]
