# Generated by Django 4.2.3 on 2023-10-25 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_customuser_user_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_limit",
        ),
    ]
