# Generated by Django 4.2.3 on 2023-10-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_customuser_user_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="limit",
            field=models.IntegerField(default=100),
        ),
    ]
