# Generated by Django 4.2.3 on 2023-10-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_customuser_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="limit",
            field=models.IntegerField(default=1000),
        ),
    ]
