# Generated by Django 4.2.3 on 2023-10-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customuser_limit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="limit",
            new_name="user_limit",
        ),
    ]
