# Generated by Django 4.2.3 on 2023-11-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_rename_limit_customuser_user_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="belt",
            field=models.CharField(
                choices=[
                    ("White", "White"),
                    ("Blue", "Blue"),
                    ("Purple", "Purple"),
                    ("Brown", "Brown"),
                    ("Black", "Black"),
                ],
                default="White",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="member_type",
            field=models.CharField(
                choices=[
                    ("Fivedays", "Fivedays"),
                    ("Eightdays", "Eightdays"),
                    ("Regular", "Regular"),
                ],
                default="Regular",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="stripes",
            field=models.IntegerField(
                choices=[
                    (0, "0 stripes"),
                    (1, "1 stripe"),
                    (2, "2 stripes"),
                    (3, "3 stripes"),
                    (4, "4 stripes"),
                ],
                default=0,
            ),
        ),
    ]
