# Generated by Django 4.2.3 on 2023-10-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("picture", models.BinaryField(editable=True, null=True)),
                (
                    "content_type",
                    models.CharField(
                        help_text="The MIMEType of the file", max_length=256, null=True
                    ),
                ),
            ],
        ),
    ]
