# Generated by Django 4.2.3 on 2023-10-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_lesson_day_lesson_spot"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="time",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
