# Generated by Django 4.2.3 on 2023-10-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_lesson_category_lesson_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="participation_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
