# Generated by Django 4.2.3 on 2023-10-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_remove_click_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="grappling_participation_count",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="jiu_jitsu_participation_count",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="kick_boxing_participation_count",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="yoga_participation_count",
        ),
    ]
