# Generated by Django 4.2.3 on 2023-10-18 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0017_remove_lesson_grappling_participation_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipationCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Jiu Jitsu", "Jiu Jitsu"),
                            ("Grappling", "Grappling"),
                            ("Kick Boxing", "Kick Boxing"),
                            ("Yoga", "Yoga"),
                        ],
                        max_length=20,
                    ),
                ),
                ("jiu_jitsu_count", models.PositiveIntegerField(default=0)),
                ("grappling_count", models.PositiveIntegerField(default=0)),
                ("kick_boxing_count", models.PositiveIntegerField(default=0)),
                ("yoga_count", models.PositiveIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
