# Generated by Django 4.2.3 on 2023-10-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_participationcount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participationcount",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="main.lesson"
            ),
        ),
    ]
