# Generated by Django 4.2.3 on 2023-10-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_remove_participationcount_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="participationcount",
            name="lesson",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.lesson",
            ),
        ),
    ]
