# Generated by Django 4.2.3 on 2023-10-18 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_participationcount_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participationcount",
            name="lesson",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.lesson",
            ),
        ),
    ]
