# Generated by Django 4.2.3 on 2023-10-19 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_participationcount_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participationcount",
            name="category",
        ),
    ]
