# Generated by Django 4.2.3 on 2023-10-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_remove_participationcount_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="school",
            field=models.CharField(
                choices=[("Kix", "Kix"), ("Iwade", "Iwade")], max_length=10, null=True
            ),
        ),
    ]
