# Generated by Django 4.2.3 on 2023-10-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_lesson_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="school",
        ),
    ]
