# Generated by Django 4.2.3 on 2023-10-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_lesson_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="category",
            field=models.CharField(
                choices=[
                    ("Jiu Jitsu", "Jiu Jitsu"),
                    ("Grappling", "Grappling"),
                    ("Competition", "Competition"),
                    ("Free Mat", "Free Mat"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
