# Generated by Django 4.2.3 on 2023-10-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_alter_lesson_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="category",
            field=models.CharField(
                choices=[
                    ("Jiu Jitsu", "Jiu Jitsu"),
                    ("Free Mat", "Free Mat"),
                    ("Competition", "Competition"),
                    ("Basic", "Basic"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
