# Generated by Django 4.2.3 on 2023-11-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_click_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participationcount",
            name="basic_count",
        ),
        migrations.RemoveField(
            model_name="participationcount",
            name="competition_count",
        ),
        migrations.RemoveField(
            model_name="participationcount",
            name="free_mat_count",
        ),
        migrations.RemoveField(
            model_name="participationcount",
            name="monthly_count_b",
        ),
        migrations.RemoveField(
            model_name="participationcount",
            name="monthly_count_c",
        ),
        migrations.RemoveField(
            model_name="participationcount",
            name="monthly_count_f",
        ),
    ]
