# Generated by Django 4.2.3 on 2023-12-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_remove_participationcount_basic_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participationcount",
            name="jiu_jitsu_count",
        ),
    ]
