# Generated by Django 4.2.3 on 2023-12-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_remove_participationcount_jiu_jitsu_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="spot",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], null=True
            ),
        ),
    ]
